# BSDRunner fallback generated colors
foreground             #d8e1ea
background             #1a2128
selection_foreground   #101418
selection_background   #b7d9f2

cursor                 #d8e1ea
cursor_text_color      #6aa9d8
url_color              #6aa9d8

active_border_color    #6aa9d8
inactive_border_color  #3c4652
bell_border_color      #ffb86b

active_tab_foreground   #101418
active_tab_background   #6aa9d8
inactive_tab_foreground #d8e1ea
inactive_tab_background #1a2128

wayland_titlebar_color #1a2128

color0  #101418
color1  #ff8f9a
color2  #6aa9d8
color3  #ffb86b
color4  #b7d9f2
color5  #7baed6
color6  #8abbdc
color7  #d8e1ea

color8  #3c4652
color9  #ffb0bb
color10 #8fc3ea
color11 #ffd2a3
color12 #d7ebfa
color13 #9fcaea
color14 #b4d6eb
color15 #f4f8fb
