#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = sh ~/.config/bsdrunner/scripts/bsdrunner-start-wallpaper.sh
exec-once = sh ~/.config/bsdrunner/scripts/bsdrunner-lid-watch.sh
exec-once = sh ~/.config/bsdrunner/scripts/bsdrunner-start-welcome.sh
exec-once = sh ~/.config/bsdrunner/scripts/bsdrunner-start-waybar.sh
# exec-once = hyprpaper & firefox
