###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = sh ~/.config/bsdrunner/scripts/bsdrunner-files.sh
$menu = hyprlauncher
